# BASE SERVER URL
BASE_URL = "https://PLACEHOLDER.com/"

# CREDENTIALS REQUEST
CREDENTIALS_URL = BASE_URL + "credentials"
CRED_USER_KEY = "username"
CRED_PASS_KEY = "password"

# AUTHENTICATION REQUEST
